# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from citipy import citipy
# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csv_path="..\WeatherPy\Output\WeatherData2020Oct30.csv"
city_weather_df=pd.read_csv(csv_path, encoding="utf-8")
city_weather_df.head()

,City,Latitude,Longitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph)
0,katsuura,35.13,140.30,64.44,51.0,20.0,11.41
1,khatanga,71.97,102.50,-9.71,86.0,0.0,5.95
2,naze,28.37,129.48,77.00,53.0,40.0,21.92
3,gat,31.61,34.76,73.94,100.0,59.0,1.99
4,tuktoyaktuk,69.45,-133.04,1.40,84.0,40.0,5.82

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
#Access gmaps with API key
gmaps.configure(api_key=g_key)
locations_df=city_weather_df[['Latitude','Longitude']]
humidity=city_weather_df['Humidity (%)']

#plot heatmap
fig=gmaps.figure()

heat_layer=gmaps.heatmap_layer(locations_df, weights=humidity,
                              dissipating=False, max_intensity=10,
                              point_radius=1)
#Add layer
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
weather_condition_df=city_weather_df.loc[(city_weather_df['Temperature (F)']<80)&(city_weather_df['Cloudiness (%)']<=60)&(city_weather_df['Humidity (%)']<50)&(city_weather_df['Wind Speed (mph)']>=5),:].reset_index(drop=True)
print(weather_condition_df.count())
weather_condition_df.head(10)

City                23
Latitude            23
Longitude           23
Temperature (F)     23
Humidity (%)        23
Cloudiness (%)      23
Wind Speed (mph)    23
dtype: int64

,City,Latitude,Longitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph)
0,gumdag,39.21,54.59,63.79,25.0,0.0,17.13
1,birjand,32.87,59.22,57.20,2.0,0.0,6.93
2,tiznit,29.58,-9.50,66.31,27.0,0.0,5.14
3,hasaki,35.73,140.83,65.14,48.0,20.0,13.87
4,gorom-gorom,14.44,-0.24,77.99,18.0,0.0,7.67
5,santa cruz,-17.80,-63.17,71.60,43.0,40.0,14.99
6,bilma,18.69,12.92,67.60,35.0,0.0,14.63
7,junin,-34.58,-60.94,46.99,45.0,0.0,5.01
8,jumla,29.27,82.18,67.51,24.0,28.0,7.99
9,buraydah,26.33,43.98,60.80,38.0,0.0,12.37

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:
#create new df
hotel_df=weather_condition_df
#hotels array that will be populated by API
hotels=[]
coords=[]
#loop through cities to call to API using coordinates
for city in range(len(hotel_df['City'])):
    lat=hotel_df.loc[city]['Latitude']
    long=hotel_df.loc[city]['Longitude']
    coordinates=(lat,long)
    coord1=f"{lat},{long}"
    coords.append(coordinates)
    params = {
        "types": "lodging",
        "location": coord1,
        "radius": 5000,
        "key": g_key
    }
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response=requests.get(base_url, params=params).json()
    
    try:
        hotels.append(response['results'][0]['name'])
    except:
        hotels.append("No hotels nearby")

#Add column to df
hotel_df['Nearest Hotel']=hotels
hotel_df.head(24)
# hotel_df.to_csv("Output/hotelsnearme.csv", encoding="utf-8",index=False, header=True)

,City,Latitude,Longitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Nearest Hotel,Country
0,gumdag,39.21,54.59,63.79,25.0,0.0,17.13,No hotels nearby,TM
1,birjand,32.87,59.22,57.20,2.0,0.0,6.93,Birjand Tourist Hotel,IR
2,tiznit,29.58,-9.50,66.31,27.0,0.0,5.14,No hotels nearby,MA
3,hasaki,35.73,140.83,65.14,48.0,20.0,13.87,Inubosaki Kanko Hotel,JP
4,gorom-gorom,14.44,-0.24,77.99,18.0,0.0,7.67,Mairie de Rambo,BF
5,santa cruz,-17.80,-63.17,71.60,43.0,40.0,14.99,Hotel Cortez,BO
6,bilma,18.69,12.92,67.60,35.0,0.0,14.63,Expeditions Ténére voyages,NE
7,junin,-34.58,-60.94,46.99,45.0,0.0,5.01,Hotel Copahue,AR
8,jumla,29.27,82.18,67.51,24.0,28.0,7.99,Hotel Sundar Rara Karnali,NP
9,buraydah,26.33,43.98,60.80,38.0,0.0,12.37,Mövenpick Hotel Qassim,SA
10,arlit,18.74,7.39,71.64,22.0,0.0,9.04,Hôtel Telwa Bungalow,NE
11,balkhash,46.84,74.98,39.20,48.0,0.0,11.18,Family,KZ
12,ponta do sol,32.67,-17.10,65.52,48.0,0.0,12.75,Hotel do Campo,PT
13,rawson,-43.30,-65.10,57.52,49.0,0.0,9.57,Hotel Punta León,AR
14,beloha,-25.17,45.05,79.23,37.0,0.0,11.48,No hotels nearby,MG
15,broken hill,-31.95,141.43,69.80,49.0,15.0,14.99,Daydream Motel & Cottages,AU
16,niono,14.25,-5.99,75.78,20.0,0.0,7.74,Hôtel Campement,ML
17,midland,32.00,-102.08,53.64,47.0,1.0,10.29,DoubleTree by Hilton Hotel Midland Plaza,US
18,shimoda,34.67,138.95,59.18,48.0,20.0,14.99,Shimoda Tokyu Hotel,JP
19,vredendal,-31.67,18.50,66.13,35.0,0.0,6.76,Tharrakamma Guest House,ZA
20,xuchang,34.02,113.82,71.60,40.0,3.0,11.18,Super 8 Hotel,CN
21,cap malheureux,-19.98,57.61,73.99,43.0,0.0,13.00,Pereybere Hotel & Spa,MU
22,mujiayingzi,42.12,118.78,52.72,33.0,0.0,20.38,Jinjiang Hotel,CN

In [34]:
#removing cities without hotels
removehotels= hotel_df.index[hotel_df['Nearest Hotel']=='No hotels nearby'].tolist()
print(removehotels)
newhotel_df=hotel_df.drop(removehotels)
newhotel_df.head(20)

[0, 2, 14]

,City,Latitude,Longitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Nearest Hotel,Country
1,birjand,32.87,59.22,57.20,2.0,0.0,6.93,Birjand Tourist Hotel,IR
3,hasaki,35.73,140.83,65.14,48.0,20.0,13.87,Inubosaki Kanko Hotel,JP
4,gorom-gorom,14.44,-0.24,77.99,18.0,0.0,7.67,Mairie de Rambo,BF
5,santa cruz,-17.80,-63.17,71.60,43.0,40.0,14.99,Hotel Cortez,BO
6,bilma,18.69,12.92,67.60,35.0,0.0,14.63,Expeditions Ténére voyages,NE
7,junin,-34.58,-60.94,46.99,45.0,0.0,5.01,Hotel Copahue,AR
8,jumla,29.27,82.18,67.51,24.0,28.0,7.99,Hotel Sundar Rara Karnali,NP
9,buraydah,26.33,43.98,60.80,38.0,0.0,12.37,Mövenpick Hotel Qassim,SA
10,arlit,18.74,7.39,71.64,22.0,0.0,9.04,Hôtel Telwa Bungalow,NE
11,balkhash,46.84,74.98,39.20,48.0,0.0,11.18,Family,KZ
12,ponta do sol,32.67,-17.10,65.52,48.0,0.0,12.75,Hotel do Campo,PT
13,rawson,-43.30,-65.10,57.52,49.0,0.0,9.57,Hotel Punta León,AR
15,broken hill,-31.95,141.43,69.80,49.0,15.0,14.99,Daydream Motel & Cottages,AU
16,niono,14.25,-5.99,75.78,20.0,0.0,7.74,Hôtel Campement,ML
17,midland,32.00,-102.08,53.64,47.0,1.0,10.29,DoubleTree by Hilton Hotel Midland Plaza,US
18,shimoda,34.67,138.95,59.18,48.0,20.0,14.99,Shimoda Tokyu Hotel,JP
19,vredendal,-31.67,18.50,66.13,35.0,0.0,6.76,Tharrakamma Guest House,ZA
20,xuchang,34.02,113.82,71.60,40.0,3.0,11.18,Super 8 Hotel,CN
21,cap malheureux,-19.98,57.61,73.99,43.0,0.0,13.00,Pereybere Hotel & Spa,MU
22,mujiayingzi,42.12,118.78,52.72,33.0,0.0,20.38,Jinjiang Hotel,CN

In [6]:
#Add country and make new df for map
Country=[]
for index, row in newhotel_df.iterrows():
    Country.append(citipy.nearest_city(row["Latitude"],row["Longitude"]).country_code.upper())
newhotel_df["Country"]=Country
newhotels=newhotel_df.loc[newhotel_df["Nearest Hotel"]!="No hotels nearby", :]
newhotels=newhotels.reset_index(drop=True)
newhotels=newhotels[["Nearest Hotel", "City", "Country"]]
newhotels

                               Nearest Hotel            City Country
0                      Birjand Tourist Hotel         birjand      IR
1                      Inubosaki Kanko Hotel          hasaki      JP
2                            Mairie de Rambo     gorom-gorom      BF
3                               Hotel Cortez      santa cruz      BO
4                 Expeditions Ténére voyages           bilma      NE
5                              Hotel Copahue           junin      AR
6                  Hotel Sundar Rara Karnali           jumla      NP
7                     Mövenpick Hotel Qassim        buraydah      SA
8                       Hôtel Telwa Bungalow           arlit      NE
9                                     Family        balkhash      KZ
10                            Hotel do Campo    ponta do sol      PT
11                          Hotel Punta León          rawson      AR
12                 Daydream Motel & Cottages     broken hill      AU
13                           Hôtel Campement           niono      ML
14  DoubleTree by Hilton Hotel Midland Plaza         midland      US
15                       Shimoda Tokyu Hotel         shimoda      JP
16                   Tharrakamma Guest House       vredendal      ZA
17                             Super 8 Hotel         xuchang      CN
18                     Pereybere Hotel & Spa  cap malheureux      MU
19                            Jinjiang Hotel     mujiayingzi      CN

In [59]:
hotelcoordinates=[]
for i,hotel in newhotel_df.iterrows():
    lat1=hotel['Latitude']
    long1=hotel['Longitude']
    hotelcoordinates.append((lat1,long1))
print(hotelcoordinates)

[(32.87, 59.22), (35.73, 140.83), (14.44, -0.24), (-17.8, -63.17), (18.69, 12.92), (-34.58, -60.94), (29.27, 82.18), (26.33, 43.98), (18.74, 7.39), (46.84, 74.98), (32.67, -17.1), (-43.3, -65.1), (-31.95, 141.43), (14.25, -5.99), (32.0, -102.08), (34.67, 138.95), (-31.67, 18.5), (34.02, 113.82), (-19.98, 57.61), (42.12, 118.78)]

In [60]:
 # NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Nearest Hotel}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in newhotels.iterrows()]
locations = hotelcoordinates

In [61]:
print(len(hotel_info))
print(len(locations))

20
20

In [62]:
# # Add marker layer ontop of heat map
markers=gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# # Display figure
fig

Figure(layout=FigureLayout(height='420px'))